kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: api
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      port: 10080
      targetPort: 10080
  selector:
    app: api
  