apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 172.16.3.221/lihualin/api-service:0.2
        command: ["api-service", "--selector", "static"]