// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: random.proto

/*
Package random is a generated protocol buffer package.

It is generated from these files:
	random.proto

It has these top-level messages:
	RandomRequest
	RandomResponse
*/
package random

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for RandomService service

type RandomService interface {
	Random(ctx context.Context, in *RandomRequest, opts ...client.CallOption) (*RandomResponse, error)
}

type randomService struct {
	c    client.Client
	name string
}

func NewRandomService(name string, c client.Client) RandomService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "random"
	}
	return &randomService{
		c:    c,
		name: name,
	}
}

func (c *randomService) Random(ctx context.Context, in *RandomRequest, opts ...client.CallOption) (*RandomResponse, error) {
	req := c.c.NewRequest(c.name, "RandomService.Random", in)
	out := new(RandomResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RandomService service

type RandomServiceHandler interface {
	Random(context.Context, *RandomRequest, *RandomResponse) error
}

func RegisterRandomServiceHandler(s server.Server, hdlr RandomServiceHandler, opts ...server.HandlerOption) {
	type randomService interface {
		Random(ctx context.Context, in *RandomRequest, out *RandomResponse) error
	}
	type RandomService struct {
		randomService
	}
	h := &randomServiceHandler{hdlr}
	s.Handle(s.NewHandler(&RandomService{h}, opts...))
}

type randomServiceHandler struct {
	RandomServiceHandler
}

func (h *randomServiceHandler) Random(ctx context.Context, in *RandomRequest, out *RandomResponse) error {
	return h.RandomServiceHandler.Random(ctx, in, out)
}
